version: '3.8'
services:
  postgres:
    image: postgres:14.5
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: development
    ports:
      - "5432:5432"
  mysql:
    image: mysql:8.0.26
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development
    ports:
      - "3306:3306"

volumes:
  pg_data:
  mysql_data: