// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/rs/xid"
)

type BulkUpsertUserInput struct {
	ID   *xid.ID `json:"id"`
	Name string  `json:"name"`
	Age  int     `json:"age"`
}
