// Code generated by protoc-gen-entgrpc. DO NOT EDIT.
package entpb

import (
	ent "blueprint/ent"
	post "blueprint/ent/post"
	context "context"
	base64 "encoding/base64"
	entproto "entgo.io/contrib/entproto"
	runtime "entgo.io/contrib/entproto/runtime"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "errors"
	fmt "fmt"
	xid "github.com/rs/xid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// PostService implements PostServiceServer
type PostService struct {
	client *ent.Client
	UnimplementedPostServiceServer
}

// NewPostService returns a new PostService
func NewPostService(client *ent.Client) *PostService {
	return &PostService{
		client: client,
	}
}

// toProtoPost transforms the ent type to the pb type
func toProtoPost(e *ent.Post) (*Post, error) {
	v := &Post{}
	content := e.Content
	v.Content = content
	created_at := timestamppb.New(e.CreatedAt)
	v.CreatedAt = created_at
	idValue, err := e.ID.Value()
	if err != nil {
		return nil, err
	}
	id, ok := idValue.(string)
	if !ok {
		return nil, errors.New("casting value to string")
	}
	v.Id = id
	updated_at := timestamppb.New(e.UpdatedAt)
	v.UpdatedAt = updated_at
	authorValue, err := e.UserID.Value()
	if err != nil {
		return nil, err
	}
	author, ok := authorValue.(string)
	if !ok {
		return nil, errors.New("casting value to string")
	}
	v.UserId = author
	return v, nil
}

// toProtoPostList transforms a list of ent type to a list of pb type
func toProtoPostList(e []*ent.Post) ([]*Post, error) {
	var pbList []*Post
	for _, entEntity := range e {
		pbEntity, err := toProtoPost(entEntity)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		pbList = append(pbList, pbEntity)
	}
	return pbList, nil
}

// Create implements PostServiceServer.Create
func (svc *PostService) Create(ctx context.Context, req *CreatePostRequest) (*Post, error) {
	post := req.GetPost()
	m, err := svc.createBuilder(post)
	if err != nil {
		return nil, err
	}
	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoPost(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Get implements PostServiceServer.Get
func (svc *PostService) Get(ctx context.Context, req *GetPostRequest) (*Post, error) {
	var (
		err error
		get *ent.Post
	)
	id := xid.ID{}
	if err := (&id).Scan(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	switch req.GetView() {
	case GetPostRequest_VIEW_UNSPECIFIED, GetPostRequest_BASIC:
		get, err = svc.client.Post.Get(ctx, id)
	case GetPostRequest_WITH_EDGE_IDS:
		get, err = svc.client.Post.Query().
			Where(post.ID(id)).
			Only(ctx)
	default:
		return nil, status.Error(codes.InvalidArgument, "invalid argument: unknown view")
	}
	switch {
	case err == nil:
		return toProtoPost(get)
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Update implements PostServiceServer.Update
func (svc *PostService) Update(ctx context.Context, req *UpdatePostRequest) (*Post, error) {
	post := req.GetPost()
	postID := xid.ID{}
	if err := (&postID).Scan(post.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	m := svc.client.Post.UpdateOneID(postID)
	postContent := post.GetContent()
	m.SetContent(postContent)
	postUpdatedAt := runtime.ExtractTime(post.GetUpdatedAt())
	m.SetUpdatedAt(postUpdatedAt)
	postUserID := xid.ID{}
	if err := (&postUserID).Scan(post.GetUserId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	m.SetUserID(postUserID)

	res, err := m.Save(ctx)
	switch {
	case err == nil:
		proto, err := toProtoPost(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return proto, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// Delete implements PostServiceServer.Delete
func (svc *PostService) Delete(ctx context.Context, req *DeletePostRequest) (*emptypb.Empty, error) {
	var err error
	id := xid.ID{}
	if err := (&id).Scan(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	err = svc.client.Post.DeleteOneID(id).Exec(ctx)
	switch {
	case err == nil:
		return &emptypb.Empty{}, nil
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// List implements PostServiceServer.List
func (svc *PostService) List(ctx context.Context, req *ListPostRequest) (*ListPostResponse, error) {
	var (
		err      error
		entList  []*ent.Post
		pageSize int
	)
	pageSize = int(req.GetPageSize())
	switch {
	case pageSize < 0:
		return nil, status.Errorf(codes.InvalidArgument, "page size cannot be less than zero")
	case pageSize == 0 || pageSize > entproto.MaxPageSize:
		pageSize = entproto.MaxPageSize
	}
	listQuery := svc.client.Post.Query().
		Order(ent.Desc(post.FieldID)).
		Limit(pageSize + 1)
	if req.GetPageToken() != "" {
		bytes, err := base64.StdEncoding.DecodeString(req.PageToken)
		if err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		pageToken, err := xid.FromBytes(bytes)
		if err != nil {
    		return nil, status.Errorf(codes.InvalidArgument, "page token is invalid")
		}
		listQuery = listQuery.
			Where(post.IDLTE(pageToken))
	}
	switch req.GetView() {
	case ListPostRequest_VIEW_UNSPECIFIED, ListPostRequest_BASIC:
		entList, err = listQuery.All(ctx)
	case ListPostRequest_WITH_EDGE_IDS:
		entList, err = listQuery.
			All(ctx)
	}
	switch {
	case err == nil:
		var nextPageToken string
		if len(entList) == pageSize+1 {
			nextPageToken = base64.StdEncoding.EncodeToString(
				[]byte(fmt.Sprintf("%v", entList[len(entList)-1].ID)))
			entList = entList[:len(entList)-1]
		}
		protoList, err := toProtoPostList(entList)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &ListPostResponse{
			PostList:      protoList,
			NextPageToken: nextPageToken,
		}, nil
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

// BatchCreate implements PostServiceServer.BatchCreate
func (svc *PostService) BatchCreate(ctx context.Context, req *BatchCreatePostsRequest) (*BatchCreatePostsResponse, error) {
	requests := req.GetRequests()
	if len(requests) > entproto.MaxBatchCreateSize {
		return nil, status.Errorf(codes.InvalidArgument, "batch size cannot be greater than %d", entproto.MaxBatchCreateSize)
	}
	bulk := make([]*ent.PostCreate, len(requests))
	for i, req := range requests {
		post := req.GetPost()
		var err error
		bulk[i], err = svc.createBuilder(post)
		if err != nil {
			return nil, err
		}
	}
	res, err := svc.client.Post.CreateBulk(bulk...).Save(ctx)
	switch {
	case err == nil:
		protoList, err := toProtoPostList(res)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "internal error: %s", err)
		}
		return &BatchCreatePostsResponse{
			Posts: protoList,
		}, nil
	case sqlgraph.IsUniqueConstraintError(err):
		return nil, status.Errorf(codes.AlreadyExists, "already exists: %s", err)
	case ent.IsConstraintError(err):
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}

}

func (svc *PostService) createBuilder(post *Post) (*ent.PostCreate, error) {
	m := svc.client.Post.Create()
	postContent := post.GetContent()
	m.SetContent(postContent)
	postCreatedAt := runtime.ExtractTime(post.GetCreatedAt())
	m.SetCreatedAt(postCreatedAt)
	postUpdatedAt := runtime.ExtractTime(post.GetUpdatedAt())
	m.SetUpdatedAt(postUpdatedAt)
	postUserID := xid.ID{}
	if err := (&postUserID).Scan(post.GetUserId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid argument: %s", err)
	}
	m.SetUserID(postUserID)
	return m, nil
}
